### ISSUE TITLE
gwtp-sample-tab Doesn't work in Chrome/Firefox

### ISSUE THREAD

**Issue by peterdresslar** [ArcBees/GWTP-Samples#87]
I can build and run gwtp-sample-tab from 01aa8ca79773ba5b281fe51047c0cec4b5a4080a (using SDM at the moment)  in the latest version, but the application doesn't run; instead the console lists Umbrella errors for containers (see below for full)

Previous version before the update (ad66651673ba0aa3ff363b4e88a18e83ad5d226e) works fine when I check out and run the same way. 

I suppose this could be GWTP-Samples or something deep in GWTP-1.5 (the POM obviously changed) but so far the other samples work.

```
Uncaught com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Exception caught: Containers must implement either HasOneWidget or HasWidgets.handleTokenChange_0_g$ @ PlaceManagerImpl.java:281revealCurrentPlace_0_g$ @ PlaceManagerImpl.java:322onBootstrap_0_g$ @ DefaultBootstrapper.java:38init_6_g$ @ ApplicationControllerImpl.java:11onModuleLoad_3_g$ @ ApplicationControllerImpl.java:15init_2_g$ @ com_00046gwtplatform_00046samples_00046tab_00046Gwtptabsample__EntryMethodHolder.java:3initializeModules_0_g$ @ ModuleUtils.java:44apply_0_g$ @ Impl.java:247entry0_0_g$ @ Impl.java:306(anonymous function) @ Impl.java:72gwtOnLoad_0_g$ @ ModuleUtils.java:55(anonymous function) @ Map.java:29
Impl.java:213Uncaught com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Containers must implement either HasOneWidget or HasWidgets.(anonymous function) @ Impl.java:213
```

**Comment by olafleur** [comment]
I probably broke something with my update today. Will look at that tomorrow morning.

**Comment by olafleur** [comment]
Everything should be fine now. Feel free to open another issue if you find another problem.
Thanks for your input!
