### ISSUE TITLE
gwtp-sample-tab Dialogs tab IllegalArgumentException

### ISSUE THREAD

**Issue by peterdresslar** [ArcBees/GWTP-Samples#89]
The Dialogs tab (the main tab, not the nested ones) in GWTP-Sample-Tab generates an exception:

Uncaught java.lang.IllegalArgumentException: Containers must implement either HasOneWidget or HasWidgets.

Removing `bindSlot` and overriding `SetInSlot` again works to resolve the exception (https://gist.github.com/peterdresslar/afc146dea4184588379a) but the example (Global, Local)  dialogs are still not working correctly once this is done.

**Comment by Elrhino** [comment]
@peterdresslar - Thank you for reporting the issue. You were not too far from fixing it! You've used HomePresenter to bind the slot instead of DialogSamplePresenter ;)
