### ISSUE TITLE
Readme link to archetypes is invalid (404)

### ISSUE THREAD

**Issue by Lanik42** [ArcBees/GWTP-Samples#93]
I'm trying to create a new GWTP project by archetype, but the link is broken.  Did the repo move?

Current link: https://github.com/ArcBees/ArcBees-tools/tree/master/archetypes

**Comment by olafleur** [comment]
Yeah, you are right. Thanks for noticing !

The correct URL is this one : 
https://github.com/ArcBees/ArcBees-archetypes/tree/master/archetypes

**Comment by olafleur** [comment]
I've fixed the link in the readme.

Thanks for your input!

**Comment by Lanik42** [comment]
Wow that was fast - thanks!
