### ISSUE TITLE
samples not in sync with tutorial part 2

### ISSUE THREAD

**Issue by fusionbeam** [ArcBees/GWTP-Samples#95]
Hi,

I'm following your tutorial http://dev.arcbees.com/gwtp/tutorials/tutorial-part2.html with an interest in the your nested sample.
However I am not able to find the actual code matching the tutorial. There is no ContactsPresenterWidget anywhere in the samples repo, no ContactsWidgetModule etc.

Thanks,
Rares

**Comment by Elrhino** [comment]
Hi @fusionbeam 

You're right, this code is not in the samples but you can find a very similar exemple [here](https://github.com/Elrhino/toaster_launcher/tree/tutorial_part2) in the project I created for this [article](http://blog.arcbees.com/2015/10/27/gwtp-beginners-tutorial-toaster-launcher-part-2/).

Keep in mind that this repo is not official so it might not be up-to-date.

**Comment by fusionbeam** [comment]
It has what I was looking for. 
Thanks a lot!
